imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    cache_bust_key_file: cache_bust_key_file
    
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
#    form:
#        resources: ['bootstrap_3_layout.html.twig']
        
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ LollypopGearBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss
        jpegoptim:
            bin: path/to/jpegoptim
            strip_all: true
            max: 50
        optipng:
            apply_to: "\.png$"
            level:    3

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  utf8mb4
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                match_against: Lollypop\GearBundle\Extension\Doctrine\MatchAgainstFunction

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    api_user_provider:
        class:     Lollypop\GearBundle\Security\ApiUserProvider
        arguments: ['@doctrine']
    api_authenticator:
        class:     Lollypop\GearBundle\Security\ApiAuthenticator
        arguments: ['@api_user_provider']
    request_listener:
        class:     Lollypop\GearBundle\EventListener\RequestListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    response_listener:
        class:     Lollypop\GearBundle\EventListener\ResponseListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        
doctrine_cache:
    providers:
        gearman_cache:
            type: file_system
            namespace: doctrine_cache.ns.gearman
            
gearman:
   # Bundles will parsed searching workers
   bundles:
      # Name of bundle
      MainBundle:

         # Bundle name
         name: LollypopGearBundle

         # Bundle search can be enabled or disabled
         active: true

         # If any include is defined, Only these namespaces will be parsed
         # Otherwise, full Bundle will be parsed
         include:
            - Services
            - EventListener

         # Namespaces this Bundle will ignore when parsing
         ignore:
            - DependencyInjection
            - Resources

   # default values
   # All these values will be used if are not overwritten in Workers or jobs
   defaults:

      # Default method related with all jobs
      # do // deprecated as of pecl/gearman 1.0.0. Use doNormal
      # doNormal
      # doBackground
      # doHigh
      # doHighBackground
      # doLow
      # doLowBackground
      method: doBackground

      # Default number of executions before job dies.
      # If annotations defined, will be overwritten
      # If empty, 0 is defined by default
      iterations: 150

      # execute callbacks after operations using Kernel events
      callbacks: true

      # Prefix in all jobs
      # If empty name will not be modified
      # Useful for rename jobs in different environments
      job_prefix: lolly

      # Autogenerate unique key in jobs/tasks if not set
      # This key is unique given a Job name and a payload serialized
      generate_unique_key: true

      # Prepend namespace when callableName is built
      # By default this variable is set as true
      workers_name_prepend_namespace: true

   # Server list where workers and clients will connect to
   # Each server must contain host and port
   # If annotations defined, will be full overwritten
   #
   # If servers empty, simple localhost server is defined by default
   # If port empty, 4730 is defined by efault
   servers:
      localhost:
         host: 127.0.0.1
         port: 4730

cayetanosoriano_hashids:
    salt: "randomwithlovefrommanginapudi"
    min_hash_length: 10
    alphabet: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    
fos_user:
    db_driver: orm     #other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Lollypop\GearBundle\Entity\User
    use_listener: false
