security:
    encoders:
        Lollypop\GearBundle\Entity\User:
            algorithm: bcrypt
        FOS\UserBundle\Model\UserInterface: sha512
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        api:
            id: api_user_provider
        fos_user_api:
            id: fos_user.user_provider.username
        administrators:
            entity: { class: LollypopGearBundle:User, property: username }
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern:    ^/admin
            http_basic: ~
        
        gear_api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: api_authenticator
        default:
            anonymous: ~
            
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/m, roles: IS_AUTHENTICATED_ANONYMOUSLY }
